//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPITEmployeeProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Collections.Generic;

    public partial class EmployeeEntities : DbContext
    {
        public EmployeeEntities()
            : base("name=EmployeeEntities")
        {
            Configuration.LazyLoadingEnabled = false;
        }

        public DbSet<T> DatabaseSet<T>() where T : class
        {
            return base.Set<T>();
        }

       
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCountryMaster> tblCountryMasters { get; set; }
        public virtual DbSet<tblDepartmentMaster> tblDepartmentMasters { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblGenderMaster> tblGenderMasters { get; set; }
        public virtual DbSet<tblMaritalStatusMaster> tblMaritalStatusMasters { get; set; }
        public virtual DbSet<tblStateMaster> tblStateMasters { get; set; }
    
        public virtual ObjectResult<sp_SearchEmployee_Result> sp_SearchEmployee(string searchText)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchEmployee_Result>("sp_SearchEmployee", searchTextParameter);
        }
    }
}
